"""Token-Markov GRPO training — Delethink-style RL-learned textual carryover.

Arm 2 of the four-arm ablation. Implements the Markovian Thinking paradigm from:
  "The Markovian Thinker: Architecture-Agnostic Linear Scaling of Reasoning"
  Aghajohari et al., ICLR 2026. https://github.com/McGill-NLP/the-markovian-thinker

Design: generation proceeds in fixed-size chunks. At each chunk boundary, old
context is deleted; only the last m tokens carry forward as the Markov state.
The model learns — via GRPO reward signal — what information to preserve in
that carryover window. Context bounding is structural, not learned, so the
Markov property is guaranteed by construction.

This module deliberately does NOT use TRL's GRPOTrainer. The multi-chunk
generation loop and the trace-level loss normalization are incompatible with
TRL's single-sequence-per-rollout assumption. We implement the training loop
directly, following Algorithm 1 from the Delethink paper.

All reward and equivalence logic is shared with grpo_baseline.py per contract.
All hyperparameters (lr, batch size, seed, etc.) are inherited from
configs/train_baseline_grpo.yaml via the config extends chain.
"""
from __future__ import annotations

import copy
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import math

import torch
import torch.nn.functional as F
from datasets import load_dataset
from tqdm import tqdm
from peft import LoraConfig, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

from src.training.grpo_baseline import (
    SYSTEM_PROMPT,
    answers_equivalent,
    extract_answer,
    make_logged_reward,
    map_keys,
    math_reward,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Chunk:
    """One chunk of a Delethink trace.

    input_ids:    token IDs fed as prompt for this chunk (query + carryover).
    response_ids: token IDs generated by the model for this chunk.
    old_log_probs: per-token log probs under the policy at rollout time (no grad).
                   Shape: (len(response_ids),). Used as the denominator in the
                   PPO importance ratio.
    """
    input_ids: torch.Tensor
    response_ids: torch.Tensor
    old_log_probs: torch.Tensor


@dataclass
class Trace:
    """A complete Delethink rollout for one problem — a sequence of chunks.

    chunks:  ordered list of Chunk objects (1 to iteration_cap).
    reward:  scalar reward assigned to the full trace (0.0 or 1.0).
    answer:  the ground-truth answer string for this problem.
    """
    chunks: list[Chunk] = field(default_factory=list)
    reward: float = 0.0
    answer: str = ""

    @property
    def total_response_tokens(self) -> int:
        """Total new tokens generated across all chunks — the trace length ℓ(τ)."""
        return sum(c.response_ids.shape[0] for c in self.chunks)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

@torch.no_grad()
def _generate_chunk(
    model: AutoModelForCausalLM,
    input_ids: torch.Tensor,
    max_new_tokens: int,
    temperature: float,
    top_p: float,
    eos_token_id: int,
) -> torch.Tensor:
    """Run one forward pass through the model and return the generated token IDs only.

    Args:
        input_ids:      1D tensor of prompt token IDs (already on model device).
        max_new_tokens: generation budget for this chunk.

    Returns:
        1D tensor of generated token IDs (not including the prompt).
    """
    input_ids_2d = input_ids.unsqueeze(0)
    attention_mask = torch.ones_like(input_ids_2d)
    out = model.generate(
        input_ids_2d,
        attention_mask=attention_mask,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=temperature,
        top_p=top_p,
        pad_token_id=eos_token_id,
        eos_token_id=eos_token_id,
    )
    return out[0, input_ids.shape[0]:]  # strip prompt prefix


@torch.no_grad()
def _chunk_log_probs(
    model: AutoModelForCausalLM,
    input_ids: torch.Tensor,
    response_ids: torch.Tensor,
) -> torch.Tensor:
    """Compute per-token log probs of response_ids given input_ids context.

    Runs one forward pass over [input_ids | response_ids] and extracts the
    log probs of the response tokens — i.e. the model's probability of having
    generated each response token given the prefix.

    Returns:
        1D tensor of shape (len(response_ids),) with log probabilities.
    """
    full_ids = torch.cat([input_ids, response_ids]).unsqueeze(0)
    logits = model(full_ids).logits[0]  # (seq_len, vocab_size)

    input_len = input_ids.shape[0]
    resp_len = response_ids.shape[0]

    # logits[i] predicts the token at position i+1.
    # To predict response_ids[t], use logits[input_len + t - 1].
    response_logits = logits[input_len - 1 : input_len + resp_len - 1]
    log_probs = F.log_softmax(response_logits, dim=-1)
    return log_probs[torch.arange(resp_len), response_ids]


@torch.no_grad()
def generate_delethink_trace(
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    query_ids: list[int],
    cfg: dict[str, Any],
    temperature: float,
    top_p: float,
) -> Trace:
    """Generate one Delethink trace for a single problem.

    Implements Algorithm 1 from the Delethink paper (Aghajohari et al., ICLR 2026).
    Three phases per trace:

      Chunk 1:  input = query.
                Generate up to C tokens.
                Fold the first `planning_prefix_tokens` of the response into query
                permanently (these capture the model's initial approach).

      Chunk l≥2: input = query (with planning prefix) + last m tokens of prev chunk.
                 Generate up to C-m tokens.
                 Stop early if EOS is produced.

    All tensor operations are no-grad. Log probs of the generated tokens are
    computed separately (also no-grad) and stored in each Chunk for use during
    the policy gradient update.

    Args:
        query_ids: tokenized prompt (list of ints, not yet a tensor).
        cfg:       token_markov config block from the merged YAML.

    Returns:
        A Trace with populated chunks and reward=0.0 (reward is filled later).
    """
    C = cfg["chunk_size_tokens"]       # per-chunk generation cap
    m = cfg["max_carryover_tokens"]    # Markov state size (last m tokens)
    I = cfg["iteration_cap"]           # max chunks per trace
    P = cfg["planning_prefix_tokens"]  # first P tokens of chunk 1 folded into query
    eos = tokenizer.eos_token_id
    device = next(model.parameters()).device

    query_t = torch.tensor(query_ids, device=device, dtype=torch.long)
    prompt_t = query_t.clone()
    trace = Trace()

    for i in range(I):
        max_new = C if i == 0 else (C - m)
        response_t = _generate_chunk(model, prompt_t, max_new, temperature, top_p, eos)

        if response_t.shape[0] == 0:
            break  # model generated nothing (edge case)

        old_lp = _chunk_log_probs(model, prompt_t, response_t)
        trace.chunks.append(Chunk(
            input_ids=prompt_t.clone(),
            response_ids=response_t.clone(),
            old_log_probs=old_lp,
        ))

        # Fold first P tokens of chunk 1 into the persistent query prefix.
        if i == 0:
            planning = response_t[:P]
            query_t = torch.cat([query_t, planning])

        # Stop at EOS.
        if response_t[-1].item() == eos:
            break

        # Build next chunk's prompt: query (+ planning prefix) + Markov carryover.
        carryover = response_t[-m:]
        prompt_t = torch.cat([query_t, carryover])

    return trace


# ---------------------------------------------------------------------------
# Batched generation (production path)
# ---------------------------------------------------------------------------

@torch.no_grad()
def _chunk_log_probs_batched(
    model: AutoModelForCausalLM,
    input_ids_batch: torch.Tensor,
    responses: list[torch.Tensor],
    prompt_len: int,
) -> list[torch.Tensor]:
    """Per-token log probs for a batch of (prompt, response) pairs in one forward pass.

    All rows in input_ids_batch share the same prompt_len; responses are right-padded
    with zeros and masked. With causal attention + masking, each row is processed
    independently — results are numerically identical to G sequential _chunk_log_probs
    calls.

    Args:
        input_ids_batch: (G, prompt_len) prompt tokens, same for all rows in chunk 1,
                         per-trace in chunks 2+.
        responses:       G tensors of (possibly different) response lengths.
        prompt_len:      number of prompt tokens per row.
    Returns:
        List of G 1-D tensors matching each response length.
    """
    G = len(responses)
    device = input_ids_batch.device
    max_resp_len = max(r.shape[0] for r in responses)
    total_len = prompt_len + max_resp_len

    full_ids = torch.zeros(G, total_len, dtype=torch.long, device=device)
    attn_mask = torch.zeros(G, total_len, dtype=torch.long, device=device)

    full_ids[:, :prompt_len] = input_ids_batch
    attn_mask[:, :prompt_len] = 1
    for g, resp in enumerate(responses):
        resp_len = resp.shape[0]
        full_ids[g, prompt_len : prompt_len + resp_len] = resp
        attn_mask[g, prompt_len : prompt_len + resp_len] = 1

    logits = model(full_ids, attention_mask=attn_mask).logits  # (G, total_len, vocab)

    results: list[torch.Tensor] = []
    for g, resp in enumerate(responses):
        resp_len = resp.shape[0]
        resp_logits = logits[g, prompt_len - 1 : prompt_len + resp_len - 1]
        log_probs = F.log_softmax(resp_logits, dim=-1)
        results.append(log_probs[torch.arange(resp_len, device=device), resp])
    return results


@torch.no_grad()
def generate_delethink_traces_batch(
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    query_ids: list[int],
    cfg: dict[str, Any],
    G: int,
    temperature: float,
    top_p: float,
) -> list[Trace]:
    """Generate G independent Delethink traces in parallel.

    Functionally identical to calling generate_delethink_trace G times, but uses
    batched model.generate calls (one per chunk) instead of G sequential calls.

    Chunk 1: all G traces share the same prompt → single model.generate(batch=G).
    Chunks 2+: each active trace has a unique prompt of the same length
               (query + P planning tokens + m carryover tokens) → torch.stack, no
               padding required. Traces that ended early (EOS in a previous chunk)
               are silently dropped from the active set.

    Old log probs are computed via one batched forward pass per chunk (replacing G
    sequential _chunk_log_probs calls).

    Args:
        G: number of independent traces to generate (num_generations).
    Returns:
        List of G Trace objects in the same order as the G generation slots.
    """
    C = cfg["chunk_size_tokens"]
    m = cfg["max_carryover_tokens"]
    I = cfg["iteration_cap"]
    P = cfg["planning_prefix_tokens"]
    eos = tokenizer.eos_token_id
    device = next(model.parameters()).device

    query_t = torch.tensor(query_ids, device=device, dtype=torch.long)

    traces = [Trace() for _ in range(G)]
    active = list(range(G))          # indices of still-generating traces
    query_t_g = [query_t.clone() for _ in range(G)]   # per-trace persistent query
    next_prompt_g: dict[int, torch.Tensor] = {}        # per-trace prompt for next chunk

    for chunk_idx in range(I):
        if not active:
            break

        n_active = len(active)
        max_new = C if chunk_idx == 0 else (C - m)

        # Build prompt batch — chunk 1 is identical for all; chunks 2+ differ per trace.
        if chunk_idx == 0:
            prompt_len = query_t.shape[0]
            input_batch = query_t.unsqueeze(0).expand(n_active, -1).contiguous()
        else:
            # All active prompts have the same length: len(query_ids) + P + m.
            prompts = [next_prompt_g[g] for g in active]
            prompt_len = prompts[0].shape[0]
            input_batch = torch.stack(prompts)

        # One model.generate call for all active traces.
        attn_mask = torch.ones_like(input_batch)
        out = model.generate(
            input_batch,
            attention_mask=attn_mask,
            max_new_tokens=max_new,
            do_sample=True,
            temperature=temperature,
            top_p=top_p,
            pad_token_id=eos,
            eos_token_id=eos,
        )

        # Extract per-trace responses; trim to first EOS inclusive.
        # (pad_token_id == eos_token_id, so trailing pads appear as EOS.)
        responses: list[torch.Tensor] = []
        for j in range(n_active):
            resp = out[j, prompt_len:]
            eos_positions = (resp == eos).nonzero(as_tuple=False)
            if len(eos_positions) > 0:
                resp = resp[: eos_positions[0].item() + 1]
            responses.append(resp)

        # One batched forward pass for all old_log_probs (replaces n_active separate passes).
        old_lps = _chunk_log_probs_batched(model, input_batch, responses, prompt_len)

        # Record chunks and advance active set.
        still_active: list[int] = []
        for j, g in enumerate(active):
            resp = responses[j]
            if resp.shape[0] == 0:
                continue  # empty response — drop trace

            traces[g].chunks.append(Chunk(
                input_ids=input_batch[j].clone(),
                response_ids=resp.clone(),
                old_log_probs=old_lps[j],
            ))

            # Fold first P tokens of chunk-1 response into the persistent query.
            if chunk_idx == 0:
                query_t_g[g] = torch.cat([query_t_g[g], resp[:P]])

            if resp[-1].item() == eos:
                continue  # natural EOS — trace complete

            # Build next prompt: persistent query + Markov carryover.
            next_prompt_g[g] = torch.cat([query_t_g[g], resp[-m:]])
            still_active.append(g)

        active = still_active

    return traces


# ---------------------------------------------------------------------------
# Reward and advantages
# ---------------------------------------------------------------------------

def score_traces(traces: list[Trace], answer: str) -> None:
    """Assign binary rewards to all traces in a group (in-place).

    Extracts the model's final answer from the last chunk of each trace.
    Score is 1.0 if the answer is mathematically equivalent to `answer`, else 0.0.
    """
    for trace in traces:
        if not trace.chunks:
            trace.reward = 0.0
            continue
        # Concatenate all chunk responses to form the full trace text.
        all_ids = torch.cat([c.response_ids for c in trace.chunks])
        full_text = trace.chunks[0].input_ids.new_zeros(0)  # dummy
        # Decode the full trace response for answer extraction.
        tokenizer_ref = None  # set externally; see generate_group_traces
        trace.answer = answer
        # Reward is set inside generate_group_traces after decoding.


def compute_grpo_advantages(rewards: list[float]) -> list[float]:
    """Normalize a group of rewards into GRPO advantages: (R - mean) / std.

    If all rewards are identical (std == 0), advantages are all 0 — no gradient
    signal, which is correct (the group provides no discriminating information).
    """
    import statistics
    mean = sum(rewards) / len(rewards)
    if len(rewards) < 2:
        return [0.0] * len(rewards)
    std = statistics.stdev(rewards)
    if std < 1e-8:
        return [0.0] * len(rewards)
    return [(r - mean) / std for r in rewards]


# ---------------------------------------------------------------------------
# Loss computation
# ---------------------------------------------------------------------------

def compute_trace_loss(
    model: AutoModelForCausalLM,
    ref_model: AutoModelForCausalLM,
    trace: Trace,
    advantage: float,
    clip_eps: float = 0.2,
    kl_coef: float = 0.001,
) -> torch.Tensor:
    """Compute the Delethink policy gradient loss for one trace.

    Loss formula (Algorithm 1 / Eq. 1 from the paper):

        L(τ) = (1 / ℓ(τ)) * Σ_{(x,y) in τ} Σ_t U(x, y, t)

    where ℓ(τ) = total response tokens across all chunks, and U is the
    per-token PPO clip objective:

        U(x, y, t) = min(r_t * A, clip(r_t, 1-ε, 1+ε) * A) - β * KL_t

    with r_t = πθ(y_t) / πθ_old(y_t) and KL_t = log πθ(y_t) - log πref(y_t).

    Note: advantage A is the same for every token in every chunk of the trace
    (trace-level reward, not step-level). This matches GRPO's group normalization.

    Args:
        trace:     a Trace generated during rollout (contains old_log_probs).
        advantage: scalar GRPO advantage for this trace.
        clip_eps:  PPO clip ratio (ε). Default 0.2.
        kl_coef:   KL penalty coefficient (β). Default 0.001 (Yuan reference).

    Returns:
        Scalar loss tensor (mean over all response tokens, normalized by ℓ(τ)).
    """
    trace_len = trace.total_response_tokens
    if trace_len == 0:
        return None

    device = trace.chunks[0].response_ids.device
    total_weighted_loss = None

    for chunk in trace.chunks:
        inp = chunk.input_ids
        resp = chunk.response_ids

        # Current policy log probs (with gradient).
        curr_lp = _chunk_log_probs_grad(model, inp, resp)

        # Old policy log probs (no grad, stored at rollout time).
        old_lp = chunk.old_log_probs.detach()

        # Reference policy log probs (no grad).
        with torch.no_grad():
            ref_lp = _chunk_log_probs(ref_model, inp, resp)

        # PPO importance ratio and clipped surrogate.
        ratio = torch.exp(curr_lp - old_lp)
        clip_ratio = torch.clamp(ratio, 1.0 - clip_eps, 1.0 + clip_eps)
        ppo_term = -torch.min(ratio * advantage, clip_ratio * advantage)

        # Per-token KL divergence (forward KL proxy: log πθ - log πref).
        kl_term = curr_lp - ref_lp

        token_loss = ppo_term + kl_coef * kl_term  # shape: (resp_len,)

        # Weight by chunk length for trace-length normalization.
        chunk_contribution = token_loss.sum()
        total_weighted_loss = (
            chunk_contribution if total_weighted_loss is None
            else total_weighted_loss + chunk_contribution
        )

    if total_weighted_loss is None:
        return None
    return total_weighted_loss / trace_len


def _chunk_log_probs_grad(
    model: AutoModelForCausalLM,
    input_ids: torch.Tensor,
    response_ids: torch.Tensor,
) -> torch.Tensor:
    """Same as _chunk_log_probs but retains the computation graph for backprop."""
    full_ids = torch.cat([input_ids, response_ids]).unsqueeze(0)
    logits = model(full_ids).logits[0]

    input_len = input_ids.shape[0]
    resp_len = response_ids.shape[0]

    response_logits = logits[input_len - 1 : input_len + resp_len - 1]
    log_probs = F.log_softmax(response_logits, dim=-1)
    return log_probs[torch.arange(resp_len), response_ids]


# ---------------------------------------------------------------------------
# Main training entry point
# ---------------------------------------------------------------------------

def train_token_markov(config: dict[str, Any], run_dir: Path) -> None:
    """Train the token-Markov GRPO arm using Delethink-style chunked rollouts.

    Implements Algorithm 1 from Aghajohari et al. (ICLR 2026) in a standalone
    training loop — no TRL GRPOTrainer. All shared hyperparameters (lr, batch
    size, seed, decay, etc.) are read from the merged config, which inherits
    from train_baseline_grpo.yaml.

    Architecture:
        1. For each batch of problems, generate G Delethink traces per problem.
        2. Decode the final chunk of each trace; apply binary math reward.
        3. Normalize rewards → GRPO advantages within each group of G.
        4. For each trace, compute the multi-chunk PPO loss (Eq. 1).
        5. Accumulate gradients and update the policy.

    Reference model: a frozen copy of the initial policy, used for the KL
    penalty term in the PPO objective. Never updated.
    """
    training = config["training"]
    tm_cfg = config["token_markov"]
    primary = config["primary"]

    is_smoke = (config.get("experiment") or {}).get("profile") == "smoke"
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model_id = primary["huggingface_repo_id"]
    tokenizer_id = primary["tokenizer_repo_id"]
    revision = primary.get("revision")
    dtype = getattr(torch, primary["dtype"])

    # Load dataset BEFORE initialising CUDA / loading model weights.
    # datasets' .map() spawns worker processes; forking after CUDA is initialised
    # causes the workers to inherit a broken CUDA context and hang indefinitely.
    # num_proc=1 is a belt-and-suspenders guard that forces single-process execution
    # so the fork never happens even if this ordering is accidentally swapped later.
    raw_dataset = load_dataset(
        "json", data_files=config["evaluation"]["path"], split="train"
    )
    dataset = raw_dataset.map(
        map_keys,
        remove_columns=[c for c in raw_dataset.column_names if c not in ("prompt", "answer")],
        num_proc=1,
    )
    logger.info("dataset ready: %d rows  |  loading model %s ...", len(dataset), model_id)
    # Smoke: 4-bit QLoRA to fit on 8 GB RTX 4060 — pipeline verification only.
    # Full: native bfloat16 on A100 80 GB.
    if is_smoke:
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=dtype,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
        )
        model = AutoModelForCausalLM.from_pretrained(
            model_id, revision=revision, quantization_config=bnb_config, device_map="auto"
        )
        peft_config = LoraConfig(
            task_type="CAUSAL_LM",
            r=8,
            lora_alpha=16,
            target_modules="all-linear",
            lora_dropout=0.05,
        )
        model = get_peft_model(model, peft_config)
    else:
        model = AutoModelForCausalLM.from_pretrained(
            model_id, revision=revision, dtype=dtype, device_map="auto"
        )
    model.train()

    # Reference model: frozen copy of the initial policy for the KL penalty term.
    # Smoke: load a separate bf16 reference (not quantized — ref is eval-only, no optimizer state).
    # Full: deepcopy before any gradient steps.
    if is_smoke:
        ref_model = AutoModelForCausalLM.from_pretrained(
            model_id, revision=revision, dtype=dtype, device_map="auto"
        )
    else:
        ref_model = copy.deepcopy(model)
    ref_model.eval()
    for p in ref_model.parameters():
        p.requires_grad_(False)

    tokenizer = AutoTokenizer.from_pretrained(
        tokenizer_id, revision=revision, trust_remote_code=True
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    if getattr(tokenizer, "init_kwargs", {}).get("tokenizer_class") == "Qwen2Tokenizer":
        tokenizer.init_kwargs["tokenizer_class"] = "Qwen2TokenizerFast"

    logger.info("model and tokenizer ready")

    optimizer = torch.optim.AdamW(
        model.parameters(), lr=training["learning_rate"]
    )

    G = training["num_generations"]        # traces per problem
    batch_sz = training["batch_size"]      # problems per step
    grad_accum = training["grad_accum_steps"]
    temperature = training.get("temperature", 1.0)
    top_p = training.get("top_p", 1.0)
    max_steps = training.get("max_steps") or int(1e9)
    num_epochs = training.get("num_epochs", 1)
    logging_steps = training.get("logging_steps", 5)
    save_steps = training.get("save_steps", 50)

    logged_reward = make_logged_reward(run_dir)

    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "resolved_config.json").write_text(json.dumps(config, indent=2))

    problems = list(dataset)

    # Precompute tokenised prompts once — reused across all epochs.
    for problem in problems:
        prompt_text = tokenizer.apply_chat_template(
            problem["prompt"], tokenize=False, add_generation_prompt=True
        )
        problem["query_ids"] = tokenizer(prompt_text, return_tensors="pt").input_ids[0].tolist()

    steps_per_epoch = math.ceil(len(problems) / batch_sz)
    total_steps = min(num_epochs * steps_per_epoch, max_steps)
    logger.info(
        "starting training — %d problems  %d epochs  %d steps  batch=%d  G=%d",
        len(problems), num_epochs, total_steps, batch_sz, G,
    )

    global_step = 0
    step_bar = tqdm(total=total_steps, desc="training", unit="step", dynamic_ncols=True)

    for epoch in range(num_epochs):
        for batch_start in range(0, len(problems), batch_sz):
            if global_step >= max_steps:
                break

            batch = problems[batch_start : batch_start + batch_sz]
            optimizer.zero_grad()
            accum_loss = None
            last_traces = []

            # Rollout phase — one transient bar across all traces in this step.
            rollout_total = len(batch) * G
            with tqdm(
                total=rollout_total,
                desc="  rollout",
                unit="trace",
                leave=False,
                dynamic_ncols=True,
            ) as rollout_bar:
                model.eval()
                for problem in batch:
                    answer = problem["answer"]
                    traces = generate_delethink_traces_batch(
                        model, tokenizer, problem["query_ids"], tm_cfg, G, temperature, top_p
                    )
                    for t in traces:
                        t.answer = answer
                    rollout_bar.update(G)
                    last_traces = traces

                    # --- Score traces ---
                    rewards = []
                    completions_for_log = []
                    for t in traces:
                        if t.chunks:
                            all_resp_ids = torch.cat([c.response_ids for c in t.chunks])
                            full_text = tokenizer.decode(all_resp_ids, skip_special_tokens=True)
                        else:
                            full_text = ""
                        completions_for_log.append(full_text)
                        pred = extract_answer(full_text)
                        r = 1.0 if (pred is not None and answers_equivalent(pred, answer)) else 0.0
                        t.reward = r
                        rewards.append(r)

                    logged_reward(completions_for_log, [answer] * G)

                    # --- Compute advantages ---
                    advantages = compute_grpo_advantages(rewards)

                    # --- Compute loss over all traces with non-zero advantage ---
                    batch_loss = None
                    for trace, adv in zip(traces, advantages):
                        if not trace.chunks or adv == 0.0:
                            continue
                        loss = compute_trace_loss(
                            model, ref_model, trace, adv,
                            clip_eps=0.2,
                            kl_coef=0.001,
                        )
                        if loss is None:
                            continue
                        batch_loss = loss if batch_loss is None else batch_loss + loss

                    if batch_loss is not None:
                        scaled = batch_loss / (G * grad_accum)
                        accum_loss = scaled if accum_loss is None else accum_loss + scaled
                model.train()

            # Backward + optimizer step.
            if accum_loss is not None and accum_loss.requires_grad:
                accum_loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            global_step += 1
            mean_reward = (
                sum(t.reward for t in last_traces) / len(last_traces)
                if last_traces else 0.0
            )
            loss_val = accum_loss.item() if accum_loss is not None else 0.0
            step_bar.set_postfix(loss=f"{loss_val:.4f}", reward=f"{mean_reward:.3f}", epoch=epoch)
            step_bar.update(1)

            if global_step % save_steps == 0:
                ckpt_dir = run_dir / f"checkpoint-{global_step}"
                model.save_pretrained(ckpt_dir)
                tokenizer.save_pretrained(ckpt_dir)
                tqdm.write(f"  checkpoint saved → {ckpt_dir}")

    step_bar.close()

    # Final checkpoint.
    final_dir = run_dir / f"checkpoint-{global_step}"
    model.save_pretrained(final_dir)
    tokenizer.save_pretrained(final_dir)
    tqdm.write(f"training complete — final checkpoint: {final_dir}")
